name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Get Develop Repo
        uses: actions/flowpodcast@develop
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/flowpodcast@develop
      - name: Deploy to Firebase
        uses: w9jds/flowpodcast@develop
        with:
          args: deploy --only hosting:forum
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
