name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
		steps:
			- name: Checkout Repo
        uses: actions/.github/workflows/main.yml@develop
        with:
          name: build
      - name: Deploy to Firebase
        uses: actions/.github/workflows/main.yml@develop
      with:
        args: deploy --only hosting:forum
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
